name: my cd workflow

on:
  workflow_run:
    workflows: ["my ci workflow"]
    types: ["completed"]
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run remote SSH command using password
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd ~/github-actions-demo
          git pull origin main
          docker compose pull
          docker compose up -d

          